version: '3.8'

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
      - ./src:/var/www/html
    restart: always

  php-fpm:
    user: www-data
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - logs:/log
    
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_EMAIL: ${SENDGRID_EMAIL}
      DOMAIN_NAME: "localhost"
    restart: always

  db:
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - db_data:/var/lib/mysql


    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always

volumes:
  db_data:
  logs:
